import { Data, IProductInput, IUserInput } from '@/types'
import { toSlug } from './utils'

import bcrypt from 'bcryptjs'

const users: IUserInput[] = [
  {
    name: 'John',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'Admin',
    address: {
      fullName: 'John Doe',
      street: '111 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jane',
    email: 'jane@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jane Harris',
      street: '222 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1002',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Jack',
    email: 'jack@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jack Ryan',
      street: '333 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1003',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Sarah',
    email: 'sarah@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Sarah Smith',
      street: '444 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1005',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Michael',
    email: 'michael@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'John Alexander',
      street: '555 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1006',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Emily',
    email: 'emily@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Emily Johnson',
      street: '666 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Alice',
    email: 'alice@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Alice Cooper',
      street: '777 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10007',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Tom',
    email: 'tom@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Tom Hanks',
      street: '888 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10008',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Linda',
    email: 'linda@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Linda Holmes',
      street: '999 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10009',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'George',
    email: 'george@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'George Smith',
      street: '101 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10010',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jessica',
    email: 'jessica@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jessica Brown',
      street: '102 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10011',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Chris',
    email: 'chris@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Chris Evans',
      street: '103 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10012',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Samantha',
    email: 'samantha@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Samantha Wilson',
      street: '104 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10013',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'David',
    email: 'david@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'David Lee',
      street: '105 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10014',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Anna',
    email: 'anna@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Anna Smith',
      street: '106 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10015',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
];

const products: IProductInput[] = [
    // Matériel Informatique
    {
      name: 'Dell OptiPlex 7090 Desktop PC',
      slug: toSlug('Dell OptiPlex 7090 Desktop PC'),
      category: 'Ordinateurs',
      images: ['/images/dell-optiplex-1.jpg', '/images/dell-optiplex-2.jpg'],
      tags: ['business', 'performance'],
      isPublished: true,
      price: 899.99,
      listPrice: 1099.99,
      brand: 'Dell',
      avgRating: 4.5,
      numReviews: 34,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 5 },
        { rating: 4, count: 12 },
        { rating: 5, count: 14 },
      ],
      numSales: 67,
      countInStock: 15,
      description: 'PC de bureau professionnel avec processeur Intel Core i7, 16GB RAM, SSD 512GB. Idéal pour les entreprises.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
    {
      name: 'HP EliteBook 850 G8 Laptop',
      slug: toSlug('HP EliteBook 850 G8 Laptop'),
      category: 'Ordinateurs portables',
      images: ['/images/hp-elitebook-1.jpg', '/images/hp-elitebook-2.jpg'],
      tags: ['portable', 'business'],
      isPublished: true,
      price: 1299.99,
      listPrice: 1499.99,
      brand: 'HP',
      avgRating: 4.7,
      numReviews: 28,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 1 },
        { rating: 3, count: 3 },
        { rating: 4, count: 8 },
        { rating: 5, count: 16 },
      ],
      numSales: 45,
      countInStock: 8,
      description: 'Ordinateur portable professionnel 15.6", Intel Core i7, 32GB RAM, écran Full HD, sécurité avancée.',
      sizes: [],
      colors: ['Argent'],
      reviews: [],
    },
    {
      name: 'Cisco Catalyst 2960-X Series Switch',
      slug: toSlug('Cisco Catalyst 2960-X Series Switch'),
      category: 'Réseaux',
      images: ['/images/cisco-switch-1.jpg', '/images/cisco-switch-2.jpg'],
      tags: ['réseau', 'entreprise'],
      isPublished: true,
      price: 650.00,
      listPrice: 750.00,
      brand: 'Cisco',
      avgRating: 4.8,
      numReviews: 19,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 1 },
        { rating: 4, count: 3 },
        { rating: 5, count: 15 },
      ],
      numSales: 32,
      countInStock: 22,
      description: 'Switch réseau managé 24 ports Gigabit Ethernet avec 4 ports SFP+, gestion avancée et sécurité.',
      sizes: [],
      colors: ['Gris'],
      reviews: [],
    },
  
    // Vidéosurveillance
    {
      name: 'Hikvision DS-2CD2143G0-I Caméra IP',
      slug: toSlug('Hikvision DS-2CD2143G0-I Caméra IP'),
      category: 'Vidéosurveillance',
      images: ['/images/hikvision-camera-1.jpg', '/images/hikvision-camera-2.jpg'],
      tags: ['sécurité', '4MP'],
      isPublished: true,
      price: 189.99,
      listPrice: 229.99,
      brand: 'Hikvision',
      avgRating: 4.6,
      numReviews: 52,
      ratingDistribution: [
        { rating: 1, count: 2 },
        { rating: 2, count: 1 },
        { rating: 3, count: 4 },
        { rating: 4, count: 15 },
        { rating: 5, count: 30 },
      ],
      numSales: 128,
      countInStock: 35,
      description: 'Caméra IP dôme 4MP avec vision nocturne infrarouge, détection de mouvement intelligente et résistance aux intempéries IP67.',
      sizes: [],
      colors: ['Blanc'],
      reviews: [],
    },
    {
      name: 'Dahua NVR4216-16P-4KS2 Enregistreur',
      slug: toSlug('Dahua NVR4216-16P-4KS2 Enregistreur'),
      category: 'Vidéosurveillance',
      images: ['/images/dahua-nvr-1.jpg', '/images/dahua-nvr-2.jpg'],
      tags: ['NVR', '16-canaux'],
      isPublished: true,
      price: 450.00,
      listPrice: 520.00,
      brand: 'Dahua',
      avgRating: 4.4,
      numReviews: 23,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 8 },
        { rating: 5, count: 9 },
      ],
      numSales: 41,
      countInStock: 12,
      description: 'Enregistreur vidéo réseau 16 canaux 4K avec PoE intégré, stockage jusqu\'à 8TB, accès distant via mobile.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
    {
      name: 'Axis P3245-LV Caméra Réseau',
      slug: toSlug('Axis P3245-LV Caméra Réseau'),
      category: 'Vidéosurveillance',
      images: ['/images/axis-camera-1.jpg', '/images/axis-camera-2.jpg'],
      tags: ['premium', 'analytics'],
      isPublished: true,
      price: 899.99,
      listPrice: 1099.99,
      brand: 'Axis',
      avgRating: 4.9,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 13 },
      ],
      numSales: 18,
      countInStock: 6,
      description: 'Caméra dôme fixe haute performance avec analyse vidéo intégrée, qualité d\'image exceptionnelle et cybersécurité renforcée.',
      sizes: [],
      colors: ['Blanc'],
      reviews: [],
    },
  
    // Sécurité Incendie
    {
      name: 'Honeywell Morley-IAS Centrale Incendie',
      slug: toSlug('Honeywell Morley-IAS Centrale Incendie'),
      category: 'Sécurité Incendie',
      images: ['/images/honeywell-central-1.jpg', '/images/honeywell-central-2.jpg'],
      tags: ['centrale', 'certifié'],
      isPublished: true,
      price: 1250.00,
      listPrice: 1450.00,
      brand: 'Honeywell',
      avgRating: 4.7,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 2 },
        { rating: 5, count: 8 },
      ],
      numSales: 24,
      countInStock: 5,
      description: 'Centrale de détection incendie adressable 2 boucles, écran LCD, protocole de communication avancé.',
      sizes: [],
      colors: ['Rouge'],
      reviews: [],
    },
    {
      name: 'Bosch FCP-500 Panneau de Contrôle',
      slug: toSlug('Bosch FCP-500 Panneau de Contrôle'),
      category: 'Sécurité Incendie',
      images: ['/images/bosch-panel-1.jpg', '/images/bosch-panel-2.jpg'],
      tags: ['panneau', 'intelligent'],
      isPublished: true,
      price: 850.00,
      listPrice: 980.00,
      brand: 'Bosch',
      avgRating: 4.5,
      numReviews: 18,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 7 },
        { rating: 5, count: 8 },
      ],
      numSales: 31,
      countInStock: 9,
      description: 'Panneau de contrôle incendie intelligent avec interface utilisateur intuitive et connectivité réseau.',
      sizes: [],
      colors: ['Rouge'],
      reviews: [],
    },
    {
      name: 'Détecteur Fumée Siemens OP720',
      slug: toSlug('Détecteur Fumée Siemens OP720'),
      category: 'Sécurité Incendie',
      images: ['/images/siemens-detector-1.jpg', '/images/siemens-detector-2.jpg'],
      tags: ['détecteur', 'optique'],
      isPublished: true,
      price: 45.00,
      listPrice: 55.00,
      brand: 'Siemens',
      avgRating: 4.3,
      numReviews: 67,
      ratingDistribution: [
        { rating: 1, count: 3 },
        { rating: 2, count: 4 },
        { rating: 3, count: 8 },
        { rating: 4, count: 25 },
        { rating: 5, count: 27 },
      ],
      numSales: 156,
      countInStock: 78,
      description: 'Détecteur de fumée optique intelligent avec compensation de dérive automatique et diagnostic avancé.',
      sizes: [],
      colors: ['Blanc'],
      reviews: [],
    },
  
    // Téléphonie
    {
      name: 'Cisco IP Phone 8845',
      slug: toSlug('Cisco IP Phone 8845'),
      category: 'Téléphonie',
      images: ['/images/cisco-phone-1.jpg', '/images/cisco-phone-2.jpg'],
      tags: ['VoIP', 'HD'],
      isPublished: true,
      price: 320.00,
      listPrice: 380.00,
      brand: 'Cisco',
      avgRating: 4.6,
      numReviews: 29,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 1 },
        { rating: 3, count: 3 },
        { rating: 4, count: 9 },
        { rating: 5, count: 15 },
      ],
      numSales: 58,
      countInStock: 25,
      description: 'Téléphone IP couleur avec écran 5 pouces, audio HD, Bluetooth et Wi-Fi intégré pour une communication professionnelle.',
      sizes: [],
      colors: ['Noir', 'Blanc'],
      reviews: [],
    },
    {
      name: 'Yealink SIP-T46S Téléphone IP',
      slug: toSlug('Yealink SIP-T46S Téléphone IP'),
      category: 'Téléphonie',
      images: ['/images/yealink-phone-1.jpg', '/images/yealink-phone-2.jpg'],
      tags: ['SIP', 'économique'],
      isPublished: true,
      price: 185.00,
      listPrice: 220.00,
      brand: 'Yealink',
      avgRating: 4.4,
      numReviews: 41,
      ratingDistribution: [
        { rating: 1, count: 2 },
        { rating: 2, count: 3 },
        { rating: 3, count: 5 },
        { rating: 4, count: 15 },
        { rating: 5, count: 16 },
      ],
      numSales: 89,
      countInStock: 42,
      description: 'Téléphone IP SIP avec écran couleur 4.3", 16 comptes SIP, audio Opus et technologie Yealink Acoustic Shield.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
    {
      name: 'Grandstream GXV3275 Vidéophone',
      slug: toSlug('Grandstream GXV3275 Vidéophone'),
      category: 'Téléphonie',
      images: ['/images/grandstream-video-1.jpg', '/images/grandstream-video-2.jpg'],
      tags: ['vidéo', 'Android'],
      isPublished: true,
      price: 275.00,
      listPrice: 325.00,
      brand: 'Grandstream',
      avgRating: 4.2,
      numReviews: 16,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 2 },
        { rating: 4, count: 6 },
        { rating: 5, count: 5 },
      ],
      numSales: 23,
      countInStock: 14,
      description: 'Vidéophone IP Android avec écran tactile 7", caméra intégrée, Wi-Fi et applications mobiles natives.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
  
    // Serveurs
    {
      name: 'HPE ProLiant DL380 Gen10 Server',
      slug: toSlug('HPE ProLiant DL380 Gen10 Server'),
      category: 'Serveurs',
      images: ['/images/hpe-server-1.jpg', '/images/hpe-server-2.jpg'],
      tags: ['serveur', 'rack'],
      isPublished: true,
      price: 2850.00,
      listPrice: 3200.00,
      brand: 'HPE',
      avgRating: 4.8,
      numReviews: 22,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 1 },
        { rating: 3, count: 1 },
        { rating: 4, count: 4 },
        { rating: 5, count: 16 },
      ],
      numSales: 35,
      countInStock: 7,
      description: 'Serveur rack 2U avec processeurs Intel Xeon Scalable, jusqu\'à 3TB de mémoire, stockage flexible et sécurité Silicon Root of Trust.',
      sizes: [],
      colors: ['Gris'],
      reviews: [],
    },
    {
      name: 'Dell PowerEdge R740 Serveur',
      slug: toSlug('Dell PowerEdge R740 Serveur'),
      category: 'Serveurs',
      images: ['/images/dell-server-1.jpg', '/images/dell-server-2.jpg'],
      tags: ['serveur', '2U'],
      isPublished: true,
      price: 3150.00,
      listPrice: 3600.00,
      brand: 'Dell',
      avgRating: 4.7,
      numReviews: 18,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 5 },
        { rating: 5, count: 11 },
      ],
      numSales: 28,
      countInStock: 4,
      description: 'Serveur 2U haute performance avec double processeur Intel Xeon, mémoire DDR4 extensible et contrôleur RAID intégré.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
  
    // Stockage
    {
      name: 'Synology DiskStation DS1821+',
      slug: toSlug('Synology DiskStation DS1821+'),
      category: 'Stockage',
      images: ['/images/synology-nas-1.jpg', '/images/synology-nas-2.jpg'],
      tags: ['NAS', '8-baies'],
      isPublished: true,
      price: 750.00,
      listPrice: 850.00,
      brand: 'Synology',
      avgRating: 4.9,
      numReviews: 36,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 1 },
        { rating: 4, count: 3 },
        { rating: 5, count: 32 },
      ],
      numSales: 72,
      countInStock: 18,
      description: 'Serveur NAS 8 baies avec processeur AMD Ryzen V1500B quad-core, 4GB DDR4, ports 10GbE et applications DSM avancées.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
    {
      name: 'QNAP TS-664 Turbo NAS',
      slug: toSlug('QNAP TS-664 Turbo NAS'),
      category: 'Stockage',
      images: ['/images/qnap-nas-1.jpg', '/images/qnap-nas-2.jpg'],
      tags: ['NAS', '4-baies'],
      isPublished: true,
      price: 520.00,
      listPrice: 580.00,
      brand: 'QNAP',
      avgRating: 4.5,
      numReviews: 24,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 1 },
        { rating: 3, count: 2 },
        { rating: 4, count: 8 },
        { rating: 5, count: 12 },
      ],
      numSales: 48,
      countInStock: 21,
      description: 'NAS 4 baies avec processeur Intel Celeron N5105 quad-core, 8GB DDR4, ports 2.5GbE et virtualisation intégrée.',
      sizes: [],
      colors: ['Blanc'],
      reviews: [],
    },
  
    // Écrans et Moniteurs
    {
      name: 'Dell UltraSharp U2723QE 27" 4K',
      slug: toSlug('Dell UltraSharp U2723QE 27" 4K'),
      category: 'Moniteurs',
      images: ['/images/dell-monitor-1.jpg', '/images/dell-monitor-2.jpg'],
      tags: ['4K', 'professionnel'],
      isPublished: true,
      price: 650.00,
      listPrice: 750.00,
      brand: 'Dell',
      avgRating: 4.6,
      numReviews: 45,
      ratingDistribution: [
        { rating: 1, count: 2 },
        { rating: 2, count: 1 },
        { rating: 3, count: 4 },
        { rating: 4, count: 15 },
        { rating: 5, count: 23 },
      ],
      numSales: 87,
      countInStock: 32,
      description: 'Moniteur 4K IPS 27" avec USB-C Hub, calibrage des couleurs d\'usine, pivotant et réglable en hauteur.',
      sizes: ['27"'],
      colors: ['Noir', 'Argent'],
      reviews: [],
    },
    {
      name: 'LG 34WK95U UltraWide 34"',
      slug: toSlug('LG 34WK95U UltraWide 34"'),
      category: 'Moniteurs',
      images: ['/images/lg-ultrawide-1.jpg', '/images/lg-ultrawide-2.jpg'],
      tags: ['ultrawide', '5K'],
      isPublished: true,
      price: 1200.00,
      listPrice: 1400.00,
      brand: 'LG',
      avgRating: 4.7,
      numReviews: 31,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 8 },
        { rating: 5, count: 20 },
      ],
      numSales: 52,
      countInStock: 15,
      description: 'Moniteur UltraWide 34" 5K2K Nano IPS avec Thunderbolt 3, HDR600 et technologies gaming avancées.',
      sizes: ['34"'],
      colors: ['Noir'],
      reviews: [],
    },
  
    // Imprimantes
    {
      name: 'Canon imageCLASS MF445dw',
      slug: toSlug('Canon imageCLASS MF445dw'),
      category: 'Imprimantes',
      images: ['/images/canon-printer-1.jpg', '/images/canon-printer-2.jpg'],
      tags: ['multifonction', 'laser'],
      isPublished: true,
      price: 380.00,
      listPrice: 450.00,
      brand: 'Canon',
      avgRating: 4.4,
      numReviews: 56,
      ratingDistribution: [
        { rating: 1, count: 3 },
        { rating: 2, count: 4 },
        { rating: 3, count: 7 },
        { rating: 4, count: 20 },
        { rating: 5, count: 22 },
      ],
      numSales: 134,
      countInStock: 28,
      description: 'Imprimante laser multifonction monochrome avec Wi-Fi, impression recto-verso automatique et chargeur de documents.',
      sizes: [],
      colors: ['Blanc'],
      reviews: [],
    },
    {
      name: 'HP Color LaserJet Pro M479fdw',
      slug: toSlug('HP Color LaserJet Pro M479fdw'),
      category: 'Imprimantes',
      images: ['/images/hp-colorlaser-1.jpg', '/images/hp-colorlaser-2.jpg'],
      tags: ['couleur', 'réseau'],
      isPublished: true,
      price: 520.00,
      listPrice: 620.00,
      brand: 'HP',
      avgRating: 4.3,
      numReviews: 43,
      ratingDistribution: [
        { rating: 1, count: 4 },
        { rating: 2, count: 2 },
        { rating: 3, count: 5 },
        { rating: 4, count: 16 },
        { rating: 5, count: 16 },
      ],
      numSales: 96,
      countInStock: 19,
      description: 'Imprimante laser couleur multifonction avec écran tactile, fax, Wi-Fi Direct et sécurité JetIntelligence.',
      sizes: [],
      colors: ['Blanc'],
      reviews: [],
    },
  
    // Accessoires Tech
    {
      name: 'APC Smart-UPS SMT1500I',
      slug: toSlug('APC Smart-UPS SMT1500I'),
      category: 'Alimentation',
      images: ['/images/apc-ups-1.jpg', '/images/apc-ups-2.jpg'],
      tags: ['UPS', '1500VA'],
      isPublished: true,
      price: 450.00,
      listPrice: 520.00,
      brand: 'APC',
      avgRating: 4.8,
      numReviews: 27,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 1 },
        { rating: 3, count: 1 },
        { rating: 4, count: 5 },
        { rating: 5, count: 20 },
      ],
      numSales: 63,
      countInStock: 16,
      description: 'Onduleur Smart-UPS 1500VA LCD avec régulation automatique de tension, interface USB et logiciel PowerChute.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
    {
      name: 'Ubiquiti UniFi Dream Machine Pro',
      slug: toSlug('Ubiquiti UniFi Dream Machine Pro'),
      category: 'Réseaux',
      images: ['/images/ubiquiti-udm-1.jpg', '/images/ubiquiti-udm-2.jpg'],
      tags: ['routeur', 'entreprise'],
      isPublished: true,
      price: 850.00,
      listPrice: 950.00,
      brand: 'Ubiquiti',
      avgRating: 4.9,
      numReviews: 38,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 1 },
        { rating: 4, count: 3 },
        { rating: 5, count: 34 },
      ],
      numSales: 67,
      countInStock: 11,
      description: 'Passerelle de sécurité tout-en-un avec contrôleur UniFi intégré, IPS/IDS, stockage 3.5" HDD et écran tactile.',
      sizes: [],
      colors: ['Noir'],
      reviews: [],
    },
    {
      name: 'Logitech MX Master 3S Souris',
      slug: toSlug('Logitech MX Master 3S Souris'),
      category: 'Périphériques',
      images: ['/images/logitech-mouse-1.jpg', '/images/logitech-mouse-2.jpg'],
      tags: ['souris', 'ergonomique'],
      isPublished: true,
      price: 95.00,
      listPrice: 110.00,
      brand: 'Logitech',
      avgRating: 4.7,
      numReviews: 89,
      ratingDistribution: [
        { rating: 1, count: 2 },
        { rating: 2, count: 3 },
        { rating: 3, count: 6 },
        { rating: 4, count: 25 },
        { rating: 5, count: 53 },
      ],
      numSales: 198,
      countInStock: 65,
      description: 'Souris sans fil premium avec capteur 8K DPI, défilement électromagnétique et connexion multi-appareils.',
      sizes: [],
      colors: ['Noir', 'Blanc', 'Rose'],
      reviews: [],
    }
  ]


const data : Data = {
    users,
    products,
    headerMenus: [
        {
          name: "L'offre du jour",
          href: '/search?tag=todays-deal',
        },
        {
          name: 'Nouveaux arrivages',
          href: '/search?tag=new-arrival',
        },
        {
          name: 'Produits de marque',
          href: '/search?tag=featured',
        },
        {
          name: 'Meilleures ventes',
          href: '/search?tag=best-seller',
        },
        {
          name: 'Historique de navigation',
          href: '/#browsing-history',
        },
        {
          name: 'Service client',
          href: '/page/customer-service',
        },
        {
          name: 'A propos',
          href: '/page/about-us',
        },
        {
          name: 'Aide',
          href: '/page/help',
        },
      ],

      carousels: [
        {
          // Cette bannière cible la sécurité, un besoin fondamental
          title: 'Équipements de Sécurité Incendie - Votre Première Ligne de Défense',
          buttonCaption:'Voir les Produits',
          image: '/images/banner1.jpg', // Image équipements incendie
          url: '/search?category=Securite-Incendie',
          isPublished: true,
        },
        {
          // Cette promotion gaming met l'accent sur l'économie réalisée
          title: 'Économisez Jusqu\'à 300$ sur les Écrans Gaming MSI',
          buttonCaption: 'Profiter de l\'Offre',
          image: '/images/banner2.jpg', // Image écran gaming MSI
          url: '/search?category=Ecrans-Gaming',
          isPublished: true,
        },
        {
          // Cette bannière technologique vise les entreprises modernes
          title: 'Solutions de Vidéosurveillance Automatisées',
          buttonCaption: 'Découvrir la Gamme',
          image: '/images/banner3.jpg', // Image caméra surveillance
          url: '/search?category=Cameras-Surveillance',
          isPublished: true,
        },
      ],
}



export default data
